export const GALLERY_ITEMS = [
  { label: 'Cérémonie laïque', variant: 'a', size: 'tall', type: 'photo', src: '/images/gallery/ceremonie.webp' },
  { label: 'Échange des vœux', variant: 'b', size: 'wide', type: 'photo', src: '/images/gallery/echange-voeux.webp' },
  { label: 'Détails de table', variant: 'c', size: 'normal', type: 'photo', src: '/images/gallery/details-table.webp' },
  { label: 'Bouquet & fleurs', variant: 'd', size: 'normal', type: 'photo', src: '/images/gallery/bouquet.webp' },
  { label: 'Robe & préparatifs', variant: 'e', size: 'tall', type: 'photo', src: '/images/gallery/robe-preparatifs.webp' },
  { label: 'Cortège', variant: 'f', size: 'normal', type: 'photo', src: '/images/gallery/cortege.webp' },
  { label: 'Réception', variant: 'g', size: 'wide', type: 'photo', src: '/images/gallery/reception.webp' },
  { label: 'Discours des témoins', variant: 'h', size: 'normal', type: 'photo', src: '/images/gallery/discours-temoins.webp' },
  { label: 'Première danse', variant: 'a', size: 'tall', type: 'photo', src: '/images/gallery/premiere-danse.webp' },
  { label: 'Lumières du soir', variant: 'b', size: 'normal', type: 'photo', src: '/images/gallery/lumieres-soir.webp' },
  { label: 'Scénographie', variant: 'c', size: 'normal', type: 'photo', src: '/images/gallery/scenographie.webp' },
  { label: 'Pièce montée', variant: 'd', size: 'normal', type: 'photo', src: '/images/gallery/piece-montee.webp' },
  { label: 'Cadeaux & mot doux', variant: 'e', size: 'normal', type: 'photo', src: '/images/gallery/cadeaux-mot-doux.webp' },
  { label: 'Dernier verre', variant: 'f', size: 'wide', type: 'photo', src: '/images/gallery/dernier-verre.webp' },
  { label: 'Alliances', variant: 'g', size: 'normal', type: 'photo', src: '/images/gallery/alliances.webp' },
  { label: 'Feu d’artifice', variant: 'h', size: 'tall', type: 'photo', src: '/images/gallery/feu-artifice.webp' },
]