export const GALLERY_ITEMS = [
  { label: 'Cérémonie laïque', variant: 'a', size: 'tall', type: 'photo', src: '/images/gallery/ceremonie.jpg' },
  { label: 'Échange des vœux', variant: 'b', size: 'wide', type: 'photo', src: '/images/gallery/echange-voeux.jpg' },
  { label: 'Détails de table', variant: 'c', size: 'normal', type: 'photo', src: '/images/gallery/details-table.jpg' },
  { label: 'Bouquet & fleurs', variant: 'd', size: 'normal', type: 'photo', src: '/images/gallery/bouquet.jpg' },
  { label: 'Robe & préparatifs', variant: 'e', size: 'tall', type: 'photo', src: '/images/gallery/robe-preparatifs.jpg' },
  { label: 'Cortège', variant: 'f', size: 'normal', type: 'photo', src: '/images/gallery/cortege.jpg' },
  { label: 'Réception', variant: 'g', size: 'wide', type: 'photo', src: '/images/gallery/reception.jpg' },
  { label: 'Discours des témoins', variant: 'h', size: 'normal', type: 'photo', src: '/images/gallery/discours-temoins.jpg' },
  { label: 'Première danse', variant: 'a', size: 'tall', type: 'photo', src: '/images/gallery/premiere-danse.jpg' },
  { label: 'Lumières du soir', variant: 'b', size: 'normal', type: 'photo', src: '/images/gallery/lumieres-soir.jpg' },
  { label: 'Scénographie', variant: 'c', size: 'normal', type: 'photo', src: '/images/gallery/scenographie.jpg' },
  { label: 'Pièce montée', variant: 'd', size: 'normal', type: 'photo', src: '/images/gallery/piece-montee.jpg' },
  { label: 'Cadeaux & mot doux', variant: 'e', size: 'normal', type: 'photo', src: '/images/gallery/cadeaux-mot-doux.jpg' },
  { label: 'Dernier verre', variant: 'f', size: 'wide', type: 'photo', src: '/images/gallery/dernier-verre.jpg' },
  { label: 'Alliances', variant: 'g', size: 'normal', type: 'photo', src: '/images/gallery/alliances.jpg' },
  { label: 'Feu d’artifice', variant: 'h', size: 'tall', type: 'photo', src: '/images/gallery/feu-artifice.jpg' },
]